### ISSUE TITLE
Requirements missing in readme

### ISSUE THREAD

**Issue by bartbog** [bernardocuteri/q_asp#2]
From my experience, at least the following are required:

* Java (clearly) 
* python2 (not having it results in error: 
```
Jul 20, 2020 1:19:02 PM it.unical.acr.qasp.Utilities runAndGetList
INFO: Command: /bin/bash -c /tmp/fmla28211205352332702261595243941821 /tmp/tempfile13974259926850230945.tmp -read-qcir -write-gq | /tmp/qcir-conv.py100199615952460303061595243941861 - -prenex -write-gq | /tmp/rareqs-nn131160796793846413811595243941863 -  returned code 134
Jul 20, 2020 1:19:02 PM it.unical.acr.qasp.Utilities runAndGetList
INFO: /bin/bash: /tmp/qcir-conv.py100199615952460303061595243941861: /usr/bin/python: bad interpreter: No such file or directory
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at it.unical.acr.qasp.QAsp.solveQCIRProgram(QAsp.java:220)
	at it.unical.acr.qasp.QAsp.solve(QAsp.java:213)
	at it.unical.acr.qasp.QAsp.main(QAsp.java:101)
```
installing python resolves the line
```
INFO: /bin/bash: /tmp/qcir-conv.py100199615952460303061595243941861: /usr/bin/python: bad interpreter: No such file or directory
```

but still, soemthing seems to be missing. Should I put RareQS somewhere? 
```
Jul 20, 2020 1:26:27 PM it.unical.acr.qasp.Utilities runAndGetList
INFO: Command: /bin/bash -c /tmp/fmla21855170453043390111595244387523 /tmp/tempfile15287017388391027071.tmp -read-qcir -write-gq | /tmp/qcir-conv.py96048812566246600861595244387556 - -prenex -write-gq | /tmp/rareqs-nn10866392572933433191595244387559 -  returned code 134
Jul 20, 2020 1:26:27 PM it.unical.acr.qasp.Utilities runAndGetList
INFO: c RAReQS-NN, Beta
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at it.unical.acr.qasp.QAsp.solveQCIRProgram(QAsp.java:220)
	at it.unical.acr.qasp.QAsp.solve(QAsp.java:213)
	at it.unical.acr.qasp.QAsp.main(QAsp.java:101)
```

**Comment by bartbog** [comment]
Was probably my problem.

Extra requirement to be added to readme:
* %@constraint line should be present (even if there is no constraint)
